<?php
// middle/routes/docs-fe-crud.php
// Genera .github/prompts/fe-crud.prompt.md
// Playbook completo para crear un módulo CRUD en el frontend
// Contenido 100% estático curado — no extrae @doc-start

function docsFeCrud(string $promptsPath): array {

  $generated = [];
  $lines = [];

  // ── Sección 1: Intro & estructura de extensión ────────────────
  $lines[] = '## QUÉ ES UNA EXTENSIÓN';
  $lines[] = '';
  $lines[] = 'Un CRUD frontend vive dentro de una **extensión** en `app/extensions/{nombre}/`.';
  $lines[] = 'Si ya existe una extensión relacionada, el CRUD puede ir como submenu o tab dentro de ella.';
  $lines[] = 'Si es un módulo completamente nuevo, se crea una carpeta nueva.';
  $lines[] = '';
  $lines[] = '```';
  $lines[] = 'app/extensions/{nombre}/';
  $lines[] = '├── index.json               ← SIEMPRE — registro, menu, flags';
  $lines[] = '├── hooks.js                 ← Solo si hay lógica de hooks';
  $lines[] = '├── lang/';
  $lines[] = '│   └── es.json              ← Textos y traducciones';
  $lines[] = '├── views/';
  $lines[] = '│   ├── sections/';
  $lines[] = '│   │   └── {crud}-list.json ← Vista principal con datatable';
  $lines[] = '│   ├── forms/';
  $lines[] = '│   │   └── {crud}-form.json ← Formulario create/edit';
  $lines[] = '│   └── parts/               ← Fragmentos para dividir views/forms grandes';
  $lines[] = '│       └── {crud}/';
  $lines[] = '│           └── parte-1.json';
  $lines[] = '└── assets/';
  $lines[] = '    ├── js/';
  $lines[] = '    │   └── {Crud}.js        ← Clase JS del CRUD (static, estándar)';
  $lines[] = '    └── css/';
  $lines[] = '        └── {crud}.css       ← Estilos específicos (solo si los necesita)';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';

  // ── Sección 2: Árbol de decisión ─────────────────────────────
  $lines[] = '## ÁRBOL DE DECISIÓN';
  $lines[] = '';
  $lines[] = '```';
  $lines[] = '¿Ya existe una extensión relacionada?';
  $lines[] = '│';
  $lines[] = '├── SÍ → Agregar el CRUD dentro de esa extensión';
  $lines[] = '│         ¿Cómo integrarlo?';
  $lines[] = '│         ├── Como submenu en index.json (ítem nuevo en menu.items[])';
  $lines[] = '│         └── Como tab dentro de una vista existente (type: "tabs")';
  $lines[] = '│';
  $lines[] = '└── NO → Crear carpeta nueva en app/extensions/{nombre}/';
  $lines[] = '          Crear index.json con hasMenu:true y el menu completo';
  $lines[] = '';
  $lines[] = '¿La vista principal es simple (solo datatable + botones)?';
  $lines[] = '├── SÍ → Un solo {crud}-list.json en sections/';
  $lines[] = '└── NO → Usar type:"tabs" para dividir en pestañas';
  $lines[] = '          Cada tab carga su sección via json_part o sections/ separadas';
  $lines[] = '';
  $lines[] = '¿El form JSON es largo (más de ~100 líneas)?';
  $lines[] = '├── NO → Un solo {crud}-form.json en forms/';
  $lines[] = '└── SÍ → Dividir en parts/: el form principal referencia partes via json_part';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';

  // ── Sección 3: index.json ─────────────────────────────────────
  $lines[] = '## index.json — REGISTRO DE EXTENSIÓN';
  $lines[] = '';
  $lines[] = '```json';
  $lines[] = '{';
  $lines[] = '  "name":        "categoria",';
  $lines[] = '  "version":     "1.0.0",';
  $lines[] = '  "enabled":     true,';
  $lines[] = '  "hasViews":    true,';
  $lines[] = '  "hasMenu":     true,';
  $lines[] = '  "hasHooks":    false,';
  $lines[] = '  "description": "Gestión de Categorías",';
  $lines[] = '  "menu": {';
  $lines[] = '    "title": "Categorías",';
  $lines[] = '    "icon":  "📂",';
  $lines[] = '    "order": 30,';
  $lines[] = '    "items": [';
  $lines[] = '      {';
  $lines[] = '        "id":    "categoria-list",';
  $lines[] = '        "title": "Categorías",';
  $lines[] = '        "view":  "sections/categoria-list",';
  $lines[] = '        "order": 1';
  $lines[] = '      }';
  $lines[] = '    ]';
  $lines[] = '  }';
  $lines[] = '}';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '**Flags importantes:**';
  $lines[] = '```';
  $lines[] = 'hasMenu: false  → extensión sin sidebar (invisible, rol de servicio)';
  $lines[] = 'hasHooks: true  → carga hooks.js de la extensión';
  $lines[] = 'hasViews: true  → la extensión tiene vistas JSON';
  $lines[] = 'enabled: false  → extensión deshabilitada globalmente';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '**Para agregar submenu en extensión existente** — solo agregar ítem a `menu.items[]`:';
  $lines[] = '```json';
  $lines[] = '{ "id": "categoria-list", "title": "Categorías", "view": "sections/categoria-list", "order": 5 }';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';

  // ── Sección 4: Vista principal (sections) ─────────────────────
  $lines[] = '## VISTA PRINCIPAL — sections/{crud}-list.json';
  $lines[] = '';
  $lines[] = 'Vista estándar de un CRUD: botones de acción + datatable.';
  $lines[] = '';
  $lines[] = '```json';
  $lines[] = '{';
  $lines[] = '  "id":      "categoriaList",';
  $lines[] = '  "title":   "{i18n:categoria.list.title}",';
  $lines[] = '  "type":    "content",';
  $lines[] = '  "scripts": ["categoria/assets/js/Categoria.js"],';
  $lines[] = '  "content": [';
  $lines[] = '    {';
  $lines[] = '      "type":    "html",';
  $lines[] = '      "order":   0,';
  $lines[] = '      "content": "<h4>{i18n:categoria.list.header}</h4>"';
  $lines[] = '    },';
  $lines[] = '    {';
  $lines[] = '      "type":    "html",';
  $lines[] = '      "order":   1,';
  $lines[] = '      "content": "<div class=\'og-flex og-gap-sm og-my-2\'><button class=\'btn btn-primary\' onclick=\'ogModal.open(\\\"categoria|forms/categoria-form\\\", {title: \\\"{i18n:categoria.modal.new.title}\\\", width: \\\"600px\\\", showFooter: false, afterRender: function(formId){Categoria.openNew(formId);}})\'> ➕ {i18n:core.add}</button></div>"';
  $lines[] = '    },';
  $lines[] = '    {';
  $lines[] = '      "type":      "component",';
  $lines[] = '      "component": "datatable",';
  $lines[] = '      "order":     2,';
  $lines[] = '      "config": {';
  $lines[] = '        "source":  "api/categoria",';
  $lines[] = '        "columns": [';
  $lines[] = '          { "id":     { "name": "i18n:categoria.col.id",     "width": "50px", "sortable": true } },';
  $lines[] = '          { "name":   { "name": "i18n:categoria.col.name",   "sortable": true } },';
  $lines[] = '          { "status": { "name": "i18n:categoria.col.status", "format": "status-badge", "width": "100px" } }';
  $lines[] = '        ],';
  $lines[] = '        "actions": {';
  $lines[] = '          "edit":   { "name": "i18n:core.edit",   "onclick": "ogModal.open(\'categoria|forms/categoria-form\', {title: \'{i18n:categoria.modal.edit.title}\', width: \'600px\', showFooter: false, afterRender: function(formId){Categoria.openEdit(formId, {id}); }})" },';
  $lines[] = '          "delete": { "name": "i18n:core.delete", "onclick": "if(confirm(\'{i18n:categoria.confirm.delete}\')) Categoria.delete({id})" }';
  $lines[] = '        }';
  $lines[] = '      }';
  $lines[] = '    }';
  $lines[] = '  ]';
  $lines[] = '}';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '**Claves:**';
  $lines[] = '- `scripts[]` → ruta relativa a `app/extensions/`. El framework carga el JS y llama `Categoria.init()` si existe.';
  $lines[] = '- `"categoria|forms/categoria-form"` → notación `extension|path` para abrir un form en modal.';
  $lines[] = '- `{id}`, `{name}` en `onclick` → el datatable interpola los valores de la fila.';
  $lines[] = '- `source: "api/categoria"` → endpoint del backend, sin slash inicial.';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';

  // ── Sección 5: Vista con tabs ─────────────────────────────────
  $lines[] = '## VISTA CON TABS — sections/{crud}-panel.json';
  $lines[] = '';
  $lines[] = 'Cuando un módulo tiene múltiples secciones (lista + estadísticas + config...):';
  $lines[] = '';
  $lines[] = '```json';
  $lines[] = '{';
  $lines[] = '  "id":    "categoriaPanel",';
  $lines[] = '  "title": "{i18n:categoria.panel.title}",';
  $lines[] = '  "type":  "tabs",';
  $lines[] = '  "tabs": [';
  $lines[] = '    {';
  $lines[] = '      "id":      "tab-list",';
  $lines[] = '      "title":   "{i18n:categoria.tab.list}",';
  $lines[] = '      "order":   1,';
  $lines[] = '      "content": [';
  $lines[] = '        { "type": "json_part", "src": "categoria|parts/categoria/lista" }';
  $lines[] = '      ]';
  $lines[] = '    },';
  $lines[] = '    {';
  $lines[] = '      "id":      "tab-stats",';
  $lines[] = '      "title":   "{i18n:categoria.tab.stats}",';
  $lines[] = '      "order":   2,';
  $lines[] = '      "content": [';
  $lines[] = '        { "type": "json_part", "src": "categoria|parts/categoria/stats" }';
  $lines[] = '      ]';
  $lines[] = '    }';
  $lines[] = '  ]';
  $lines[] = '}';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '`json_part` carga el fragmento `parts/categoria/lista.json` dentro del tab.';
  $lines[] = 'Esto permite dividir views grandes sin duplicar lógica.';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';

  // ── Sección 6: Form JSON ──────────────────────────────────────
  $lines[] = '## FORMULARIO — forms/{crud}-form.json';
  $lines[] = '';
  $lines[] = '```json';
  $lines[] = '{';
  $lines[] = '  "id": "categoria-form",';
  $lines[] = '  "fields": [';
  $lines[] = '    {';
  $lines[] = '      "name":    "group-basic",';
  $lines[] = '      "type":    "group",';
  $lines[] = '      "columns": 2,';
  $lines[] = '      "gap":     "normal",';
  $lines[] = '      "fields": [';
  $lines[] = '        {';
  $lines[] = '          "name":       "name",';
  $lines[] = '          "label":      "i18n:categoria.field.name",';
  $lines[] = '          "type":       "text",';
  $lines[] = '          "validation": "required|min:2|max:100",';
  $lines[] = '          "placeholder":"i18n:categoria.field.name.placeholder"';
  $lines[] = '        },';
  $lines[] = '        {';
  $lines[] = '          "name":    "parent_id",';
  $lines[] = '          "label":   "i18n:categoria.field.parent",';
  $lines[] = '          "type":    "select",';
  $lines[] = '          "source":  "/api/categoria?status=1",';
  $lines[] = '          "sourceValue": "id",';
  $lines[] = '          "sourceLabel": "name",';
  $lines[] = '          "options": [{ "value": "", "label": "i18n:core.form.select.placeholder" }]';
  $lines[] = '        }';
  $lines[] = '      ]';
  $lines[] = '    },';
  $lines[] = '    {';
  $lines[] = '      "name":  "description",';
  $lines[] = '      "label": "i18n:categoria.field.description",';
  $lines[] = '      "type":  "textarea",';
  $lines[] = '      "rows":  2';
  $lines[] = '    },';
  $lines[] = '    {';
  $lines[] = '      "name":    "status",';
  $lines[] = '      "label":   "i18n:core.status.active",';
  $lines[] = '      "type":    "checkbox",';
  $lines[] = '      "default": true';
  $lines[] = '    },';
  $lines[] = '    { "name": "cancel", "type": "button", "label": "i18n:core.cancel",  "action": "cancel" },';
  $lines[] = '    { "name": "submit", "type": "button", "label": "i18n:core.save",    "action": "submit", "onclick": "Categoria.save(\'{form_id}\')" }';
  $lines[] = '  ]';
  $lines[] = '}';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '**Campos clave del form:**';
  $lines[] = '```';
  $lines[] = 'type: text | textarea | select | checkbox | repeatable | grouper | html | button | url | time';
  $lines[] = 'validation: "required|min:2|max:100|decimal|email"';
  $lines[] = 'source: "/api/recurso"    → select dinámico desde API';
  $lines[] = 'sourceValue / sourceLabel → campos del objeto API para value y label';
  $lines[] = '"config.campo"            → notación punto para campos anidados (se mapean a objeto config)';
  $lines[] = 'default: valor            → valor inicial del campo';
  $lines[] = 'hint: "i18n:..."         → texto de ayuda bajo el campo';
  $lines[] = 'className: "..."         → clases CSS extra al input';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '**group** — agrupar campos en columnas:';
  $lines[] = '```json';
  $lines[] = '{ "name": "group-info", "type": "group", "columns": 3, "gap": "normal", "fields": [...] }';
  $lines[] = '```';
  $lines[] = '> ⚠️ El campo `"name"` en `group` es **obligatorio** — sin él las condiciones basadas en contexto no funcionan.';
  $lines[] = '';
  $lines[] = '**grouper** — pestañas dentro del form (para forms muy largos):';
  $lines[] = '```json';
  $lines[] = '{ "name": "config.messages", "type": "grouper", "mode": "tabs", "activeIndex": 0, "groups": [';
  $lines[] = '  { "name": "tab1", "title": "i18n:...", "fields": [...] },';
  $lines[] = '  { "name": "tab2", "title": "i18n:...", "fields": [...] }';
  $lines[] = ']}';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '**repeatable** — lista dinámica de campos:';
  $lines[] = '```json';
  $lines[] = '{';
  $lines[] = '  "name": "config.items", "type": "repeatable",';
  $lines[] = '  "accordion": true, "sortable": true,';
  $lines[] = '  "addText": "i18n:core.add", "removeText": "i18n:core.remove",';
  $lines[] = '  "fields": [';
  $lines[] = '    { "name": "title", "type": "text", "label": "i18n:..." },';
  $lines[] = '    { "name": "value", "type": "text", "label": "i18n:..." }';
  $lines[] = '  ]';
  $lines[] = '}';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';

  // ── Sección 7: parts ──────────────────────────────────────────
  $lines[] = '## PARTS — Dividir views o forms grandes';
  $lines[] = '';
  $lines[] = 'Los `parts/` permiten partir cualquier JSON largo en fragmentos reutilizables.';
  $lines[] = '';
  $lines[] = '**Referenciar un part desde una vista o tab:**';
  $lines[] = '```json';
  $lines[] = '{ "type": "json_part", "src": "categoria|parts/categoria/lista" }';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '**El part mismo** (`parts/categoria/lista.json`) — es un fragmento de content[]:';
  $lines[] = '```json';
  $lines[] = '[';
  $lines[] = '  { "type": "html",      "content": "<h5>Lista</h5>", "order": 0 },';
  $lines[] = '  { "type": "component", "component": "datatable",    "order": 1, "config": { ... } }';
  $lines[] = ']';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = 'Organización recomendada para CRUD con múltiples parts:';
  $lines[] = '```';
  $lines[] = 'parts/categoria/';
  $lines[] = '├── lista.json       ← datatable + botones';
  $lines[] = '├── stats.json       ← gráficas o métricas';
  $lines[] = '└── config.json      ← configuración del módulo';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';

  // ── Sección 8: JS del CRUD ────────────────────────────────────
  $lines[] = '## JS DEL CRUD — assets/js/{Crud}.js';
  $lines[] = '';
  $lines[] = 'El framework carga el JS declarado en `scripts[]` de la vista y llama `{Clase}.init()` si existe.';
  $lines[] = 'El nombre de la clase debe coincidir con el nombre del archivo (sin extensión).';
  $lines[] = '';
  $lines[] = '**Cómo lo resuelve el framework:**';
  $lines[] = '```';
  $lines[] = 'scripts: ["categoria/assets/js/Categoria.js"]';
  $lines[] = '→ Carga el archivo';
  $lines[] = '→ Busca window["Categoria"] (nombre del archivo sin .js)';
  $lines[] = '→ Si tiene .init() → lo ejecuta automáticamente al cargar la vista';
  $lines[] = '→ window.Categoria queda disponible globalmente para el onclick del HTML';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '**Plantilla estándar del JS de CRUD:**';
  $lines[] = '```js';
  $lines[] = 'class Categoria {';
  $lines[] = '  // APIs del módulo';
  $lines[] = '  static apis = {';
  $lines[] = '    list:   \'/api/categoria\',';
  $lines[] = '    single: \'/api/categoria\'   // mismo endpoint, GET /{id}';
  $lines[] = '  };';
  $lines[] = '';
  $lines[] = '  static currentId = null;   // ID del registro en edición';
  $lines[] = '';
  $lines[] = '  // Llamado automáticamente por el framework al cargar la vista';
  $lines[] = '  static init() {';
  $lines[] = '    this.initFormatters();';
  $lines[] = '    // Inicializaciones extras si son necesarias';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  // Registrar formatters personalizados del datatable';
  $lines[] = '  static initFormatters() {';
  $lines[] = '    ogDatatable.registerFormatter(\'categoria-status\', (value) => {';
  $lines[] = '      const isActive  = value == 1;';
  $lines[] = '      const text  = isActive ? __(\'core.status.active\') : __(\'core.status.inactive\');';
  $lines[] = '      const color = isActive ? \'#16a34a\' : \'#dc2626\';';
  $lines[] = '      const bg    = isActive ? \'#dcfce7\'  : \'#fee2e2\';';
  $lines[] = '      return `<span style="padding:0.25rem 0.75rem;border-radius:0.375rem;font-size:0.875rem;font-weight:500;color:${color};background:${bg};">${text}</span>`;';
  $lines[] = '    });';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  // Llamado desde afterRender del modal al crear';
  $lines[] = '  static openNew(formId) {';
  $lines[] = '    this.currentId = null;';
  $lines[] = '    const realId = document.getElementById(formId)?.getAttribute(\'data-real-id\') || formId;';
  $lines[] = '    ogForm.clearAllErrors(realId);';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  // Llamado desde afterRender del modal al editar';
  $lines[] = '  static async openEdit(formId, id) {';
  $lines[] = '    this.currentId = id;';
  $lines[] = '    const realId = document.getElementById(formId)?.getAttribute(\'data-real-id\') || formId;';
  $lines[] = '    ogForm.clearAllErrors(realId);';
  $lines[] = '    const data = await this.get(id);';
  $lines[] = '    if (data) this.fillForm(formId, data);';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  // Llenar formulario con datos existentes';
  $lines[] = '  static fillForm(formId, data) {';
  $lines[] = '    ogForm.fill(formId, {';
  $lines[] = '      name:        data.name        || \'\',';
  $lines[] = '      description: data.description || \'\',';
  $lines[] = '      parent_id:   data.parent_id   ? String(data.parent_id) : \'\',';
  $lines[] = '      status:      data.status == 1';
  $lines[] = '      // Para campos anidados en config: \'config.campo\': data.config?.campo';
  $lines[] = '    });';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  // Guardar — create o update según currentId';
  $lines[] = '  static async save(formId) {';
  $lines[] = '    const validation = ogForm.validate(formId);';
  $lines[] = '    if (!validation.success) return ogToast.error(validation.message);';
  $lines[] = '';
  $lines[] = '    const body   = this.buildBody(validation.data);';
  $lines[] = '    const result = this.currentId';
  $lines[] = '      ? await this.update(this.currentId, body)';
  $lines[] = '      : await this.create(body);';
  $lines[] = '';
  $lines[] = '    if (result) {';
  $lines[] = '      ogToast.success(this.currentId';
  $lines[] = '        ? __(\'categoria.success.updated\')';
  $lines[] = '        : __(\'categoria.success.created\')';
  $lines[] = '      );';
  $lines[] = '      setTimeout(() => { ogModal.closeAll(); this.refresh(); }, 100);';
  $lines[] = '    }';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  // Transformar datos del form al formato que espera la API';
  $lines[] = '  static buildBody(formData) {';
  $lines[] = '    return {';
  $lines[] = '      name:        formData.name,';
  $lines[] = '      description: formData.description || null,';
  $lines[] = '      parent_id:   formData.parent_id ? parseInt(formData.parent_id) : null,';
  $lines[] = '      status:      formData.status ? 1 : 0';
  $lines[] = '      // Si hay campos anidados: config: { campo: formData.config?.campo }';
  $lines[] = '    };';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  // ── CRUD API ─────────────────────────────────────────────────';
  $lines[] = '';
  $lines[] = '  static async get(id) {';
  $lines[] = '    try {';
  $lines[] = '      const res = await ogApi.get(`${this.apis.single}/${id}`);';
  $lines[] = '      return res.success === false ? null : (res.data || res);';
  $lines[] = '    } catch (e) {';
  $lines[] = '      ogToast.error(__(\'categoria.error.load_failed\')); return null;';
  $lines[] = '    }';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  static async create(data) {';
  $lines[] = '    try {';
  $lines[] = '      const res = await ogApi.post(this.apis.list, data);';
  $lines[] = '      return res.success === false ? null : (res.data || res);';
  $lines[] = '    } catch (e) {';
  $lines[] = '      ogToast.error(__(\'categoria.error.create_failed\')); return null;';
  $lines[] = '    }';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  static async update(id, data) {';
  $lines[] = '    try {';
  $lines[] = '      const res = await ogApi.put(`${this.apis.single}/${id}`, { ...data, id });';
  $lines[] = '      return res.success === false ? null : (res.data || res);';
  $lines[] = '    } catch (e) {';
  $lines[] = '      ogToast.error(__(\'categoria.error.update_failed\')); return null;';
  $lines[] = '    }';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  static async delete(id) {';
  $lines[] = '    try {';
  $lines[] = '      const res = await ogApi.delete(`${this.apis.single}/${id}`);';
  $lines[] = '      if (res.success === false) { ogToast.error(__(\'categoria.error.delete_failed\')); return null; }';
  $lines[] = '      ogToast.success(__(\'categoria.success.deleted\'));';
  $lines[] = '      this.refresh();';
  $lines[] = '      return res.data || res;';
  $lines[] = '    } catch (e) {';
  $lines[] = '      ogToast.error(__(\'categoria.error.delete_failed\')); return null;';
  $lines[] = '    }';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  // Refrescar datatable';
  $lines[] = '  static refresh() {';
  $lines[] = '    if (window.ogDatatable) ogDatatable.refreshFirst();';
  $lines[] = '  }';
  $lines[] = '}';
  $lines[] = '';
  $lines[] = '// Exponer globalmente — necesario para los onclick del HTML de la vista';
  $lines[] = 'window.Categoria = Categoria;';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '**Reglas del JS:**';
  $lines[] = '- Clase con métodos `static` — nunca se instancia';
  $lines[] = '- Nombre del archivo = nombre de la clase = nombre en `window`';
  $lines[] = '- `static init()` → se ejecuta automáticamente al cargar la vista';
  $lines[] = '- `openNew(formId)` / `openEdit(formId, id)` → llamados desde `afterRender` del modal';
  $lines[] = '- `fillForm` usa `ogForm.fill()` — los keys deben coincidir exactamente con los `name` del form JSON';
  $lines[] = '- `buildBody` transforma y limpia los datos antes de enviarlos a la API';
  $lines[] = '- `save()` decide create vs update según `this.currentId`';
  $lines[] = '- Siempre `try/catch` en las llamadas a API';
  $lines[] = '- Siempre `window.ClaseName = ClaseName` al final';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';

  // ── Sección 9: CSS ────────────────────────────────────────────
  $lines[] = '## CSS DE EXTENSIÓN — assets/css/{crud}.css';
  $lines[] = '';
  $lines[] = 'Solo crear si la extensión necesita estilos que el framework no cubre.';
  $lines[] = 'Declararlo en la vista o en el `index.json` de la extensión:';
  $lines[] = '';
  $lines[] = '```json';
  $lines[] = '{ "styles": ["categoria/assets/css/categoria.css"] }';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = 'Usar alta especificidad para evitar conflictos con el CSS del framework:';
  $lines[] = '```css';
  $lines[] = '.categoria-card { display: flex !important; gap: 1rem !important; }';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';

  // ── Sección 10: Idioma ────────────────────────────────────────
  $lines[] = '## IDIOMA — lang/es.json';
  $lines[] = '';
  $lines[] = '```json';
  $lines[] = '{';
  $lines[] = '  "categoria": {';
  $lines[] = '    "list": { "title": "Categorías", "header": "Lista de Categorías" },';
  $lines[] = '    "modal": {';
  $lines[] = '      "new":  { "title": "Nueva Categoría" },';
  $lines[] = '      "edit": { "title": "Editar Categoría" }';
  $lines[] = '    },';
  $lines[] = '    "field": {';
  $lines[] = '      "name":        { "label": "Nombre", "placeholder": "Ej: Marketing" },';
  $lines[] = '      "description": { "label": "Descripción" },';
  $lines[] = '      "parent":      { "label": "Categoría Padre" }';
  $lines[] = '    },';
  $lines[] = '    "col":     { "id": "ID", "name": "Nombre", "status": "Estado" },';
  $lines[] = '    "confirm": { "delete": "¿Eliminar esta categoría?" },';
  $lines[] = '    "success": { "created": "Categoría creada", "updated": "Categoría actualizada", "deleted": "Categoría eliminada" },';
  $lines[] = '    "error":   { "load_failed": "Error al cargar", "create_failed": "Error al crear", "update_failed": "Error al actualizar", "delete_failed": "Error al eliminar" }';
  $lines[] = '  }';
  $lines[] = '}';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = 'Uso en JS: `__(\'categoria.success.created\')` — acceso por punto.';
  $lines[] = 'Uso en JSON (campo label/placeholder/title): `"i18n:categoria.field.name.label"` — prefijo `i18n:`.';
  $lines[] = 'Uso en JSON (dentro de strings HTML): `{i18n:categoria.field.name.label}` — interpolado por `viewRender`.';
  $lines[] = '';
  $lines[] = 'La interpolación `{i18n:key}` funciona en cualquier string de `content` que el motor renderice:';
  $lines[] = '```json';
  $lines[] = '{ "type": "html", "content": "Este es un texto {i18n:categoria.list.header} traducido" }';
  $lines[] = '```';
  $lines[] = 'También soporta parámetros: `{i18n:key|param1:valor1|param2:valor2}`.';
  $lines[] = 'Lo procesa `ogViewRender.processI18nInString()` antes de insertar el HTML en el DOM.';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';

  // ── Sección 11: Checklist ─────────────────────────────────────
  $lines[] = '## CHECKLIST — CREAR UN CRUD FRONTEND';
  $lines[] = '';
  $lines[] = '```';
  $lines[] = '□ 1. ¿Nueva extensión o agregar a una existente?';
  $lines[] = '       Nueva  → crear carpeta app/extensions/{nombre}/ + index.json completo';
  $lines[] = '       Existe → agregar ítem en menu.items[] del index.json existente';
  $lines[] = '';
  $lines[] = '□ 2. Crear views/sections/{crud}-list.json';
  $lines[] = '       type: "content", scripts: ["{ext}/assets/js/{Crud}.js"]';
  $lines[] = '       Botón nuevo con ogModal.open() + afterRender: {Crud}.openNew(formId)';
  $lines[] = '       Componente datatable con source, columns, actions (edit + delete)';
  $lines[] = '';
  $lines[] = '□ 3. Crear views/forms/{crud}-form.json';
  $lines[] = '       id del form, fields[], group para columnas, botones cancel+submit';
  $lines[] = '       submit.onclick: {Crud}.save(\'{form_id}\')';
  $lines[] = '';
  $lines[] = '□ 4. Crear assets/js/{Crud}.js';
  $lines[] = '       static apis = { list: \'/api/{recurso}\' }';
  $lines[] = '       static currentId = null';
  $lines[] = '       init(), initFormatters(), openNew(), openEdit(), fillForm()';
  $lines[] = '       save(), buildBody(), get(), create(), update(), delete(), refresh()';
  $lines[] = '       window.{Crud} = {Crud}  ← al final siempre';
  $lines[] = '';
  $lines[] = '□ 5. Crear lang/es.json';
  $lines[] = '       Todos los keys referenciados con i18n: en las vistas y JS';
  $lines[] = '';
  $lines[] = '□ 6. ¿Necesita CSS propio?';
  $lines[] = '       SÍ → crear assets/css/{crud}.css + agregar "styles" en la vista';
  $lines[] = '       NO → usar clases del framework (og-grid, btn, alert, og-flex, etc.)';
  $lines[] = '';
  $lines[] = '□ 7. ¿El form o la vista es muy larga?';
  $lines[] = '       SÍ → mover secciones a parts/{crud}/ y referenciar con json_part';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';

  // ── Sección 12: Notaciones de ruta ───────────────────────────
  $lines[] = '## NOTACIONES DE RUTA — dónde va cada path';
  $lines[] = '';
  $lines[] = '```';
  $lines[] = 'En onclick/scripts del JSON de vista:';
  $lines[] = '  "categoria|forms/categoria-form"   → extensión|ruta (sin .json)';
  $lines[] = '  "middle:dashboard/dashboard"        → middle:ruta';
  $lines[] = '  "core:user/user-list"               → core:ruta del framework';
  $lines[] = '';
  $lines[] = 'En scripts[] de la vista:';
  $lines[] = '  "categoria/assets/js/Categoria.js" → relativo a app/extensions/';
  $lines[] = '';
  $lines[] = 'En styles[] de la vista:';
  $lines[] = '  "categoria/assets/css/categoria.css"';
  $lines[] = '';
  $lines[] = 'En source del datatable:';
  $lines[] = '  "api/categoria"                     → sin / inicial, URL relativa';
  $lines[] = '';
  $lines[] = 'En source de select del form:';
  $lines[] = '  "/api/categoria?status=1"           → con / inicial, URL absoluta';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';

  // ── Sección 13: Errores comunes ───────────────────────────────
  $lines[] = '## ERRORES COMUNES';
  $lines[] = '';
  $lines[] = '```';
  $lines[] = 'NO distinto nombre de clase y nombre de archivo  → el framework no la encuentra';
  $lines[] = 'NO olvidar window.Clase = Clase al final         → onclick del HTML no funciona';
  $lines[] = 'NO redeclarar formatters en cada llamada         → registrar solo en init()';
  $lines[] = 'NO currentId = id en openNew()                   → quedará en modo update';
  $lines[] = 'NO usar rutas absolutas en scripts[]             → relativas a app/extensions/';
  $lines[] = 'NO /api en source del datatable                  → usar "api/recurso" sin slash';
  $lines[] = 'NO mezclar keys de i18n: en JS y formato texto   → en JS usar __(), en JSON i18n:';
  $lines[] = 'NO llenar form con data.config como string       → parsear JSON.parse si es string';
  $lines[] = 'NO ignorar el data-real-id del formId            → el modal puede remapear el ID';
  $lines[] = '```';

  // ── Armar prompt ──────────────────────────────────────────────
  $md   = [];
  $md[] = '# Frontend — Playbook CRUD & Extensiones';
  $md[] = '';
  $md[] = '> Cómo crear un módulo CRUD en el frontend. Qué archivos crear, dónde van, cómo se conectan.';
  $md[] = '> Generado: ' . date('Y-m-d H:i:s');
  $md[] = '';
  $md[] = '---';
  $md[] = '';
  $md[] = implode("\n", $lines);

  file_put_contents($promptsPath . '/fe-crud.prompt.md', implode("\n", $md));
  $generated[] = '.github/prompts/fe-crud.prompt.md';

  return compact('generated');
}