<?php
// middle/routes/docs-crud.php
// Genera .github/prompts/crud.prompt.md
// Playbook para crear módulos CRUD backend — contenido curado, no extrae @doc-start

function docsCrud(string $promptsPath): array {

  $generated = [];
  $lines = [];

  $lines[] = '## CÓMO FUNCIONA EL MOTOR (ogApi)';
  $lines[] = '';
  $lines[] = 'Cada request `/api/{modulo}` dispara este flujo en `ogApi.php`:';
  $lines[] = '';
  $lines[] = '```';
  $lines[] = 'PASO 1 — Auto-registra 5 rutas CRUD desde {modulo}.json (busca app → middle → framework)';
  $lines[] = '         Intenta cargar {Modulo}Controller — si no existe usa ogController genérico';
  $lines[] = 'PASO 2 — Carga framework/routes/{modulo}.php si existe';
  $lines[] = 'PASO 3 — Carga middle/routes/{modulo}.php si existe';
  $lines[] = 'PASO 4 — Carga app/routes/{modulo}.php si existe   ← rutas custom';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = 'Las rutas custom (PASO 4) se suman a las 5 CRUD — no las reemplazan.';
  $lines[] = 'El archivo `routes/{modulo}.php` solo es necesario si hay endpoints fuera del CRUD estándar.';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';
  $lines[] = '## ÁRBOL DE DECISIÓN — QUÉ ARCHIVOS CREAR';
  $lines[] = '';
  $lines[] = '```';
  $lines[] = '¿El CRUD estándar (list/show/create/update/delete) cubre todo sin cambios?';
  $lines[] = '│';
  $lines[] = '├── SÍ → Solo crear {modulo}.json — ogController lo cubre todo';
  $lines[] = '│';
  $lines[] = '└── NO → Crear {Modulo}Controller.php extends ogController';
  $lines[] = '          Sobreescribir solo los métodos que necesitan cambio';
  $lines[] = '          │';
  $lines[] = '          ├── ¿La lógica extra vive solo dentro del Controller?';
  $lines[] = '          │    └── No crear Handler';
  $lines[] = '          │';
  $lines[] = '          └── ¿Hay side-effects (archivos, APIs, emails) o la lógica';
  $lines[] = '               se reutiliza desde otros módulos/rutas/bots/webhooks?';
  $lines[] = '               └── Crear {Modulo}Handler.php — métodos static puros';
  $lines[] = '';
  $lines[] = '¿Hay endpoints fuera de list/show/create/update/delete?';
  $lines[] = '├── NO → No crear app/routes/{modulo}.php';
  $lines[] = '└── SÍ → Crear app/routes/{modulo}.php';
  $lines[] = '          Solo declarar los endpoints extra — las 5 CRUD no van aquí';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';
  $lines[] = '## DÓNDE VAN LOS ARCHIVOS';
  $lines[] = '';
  $lines[] = '```';
  $lines[] = 'backend/app/';
  $lines[] = '├── resources/';
  $lines[] = '│   ├── schemas/{modulo}.json           ← SIEMPRE — habilita las 5 rutas CRUD';
  $lines[] = '│   ├── controllers/{Modulo}Controller.php  ← Si hay lógica custom en los métodos CRUD';
  $lines[] = '│   └── handlers/{Modulo}Handler.php        ← Si hay side-effects o lógica reutilizable';
  $lines[] = '└── routes/{modulo}.php                 ← Solo si hay endpoints no estándar';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = 'Búsqueda automática: `app/` → `middle/` → `framework/`. Siempre trabajar en `app/`.';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';
  $lines[] = '## SCHEMA — {modulo}.json';
  $lines[] = '';
  $lines[] = '```json';
  $lines[] = '{';
  $lines[] = '  "resource":   "sale",';
  $lines[] = '  "table":      "sales",';
  $lines[] = '  "timestamps": true,';
  $lines[] = '  "middleware": ["throttle:100,1"],';
  $lines[] = '  "routes": {';
  $lines[] = '    "list":   { "method": "GET",    "path": "/api/sale",      "middleware": ["auth"] },';
  $lines[] = '    "show":   { "method": "GET",    "path": "/api/sale/{id}", "middleware": ["auth"] },';
  $lines[] = '    "create": { "method": "POST",   "path": "/api/sale",      "middleware": ["auth", "json"] },';
  $lines[] = '    "update": { "method": "PUT",    "path": "/api/sale/{id}", "middleware": ["auth", "json"] },';
  $lines[] = '    "delete": { "method": "DELETE", "path": "/api/sale/{id}", "middleware": ["auth"] }';
  $lines[] = '  },';
  $lines[] = '  "fields": [';
  $lines[] = '    { "name": "user_id", "type": "int",      "required": true },';
  $lines[] = '    { "name": "name",    "type": "string",   "required": true, "maxLength": 100 },';
  $lines[] = '    { "name": "status",  "type": "tinyint",  "default": 1 },';
  $lines[] = '    { "name": "dc",      "type": "datetime" },';
  $lines[] = '    { "name": "du",      "type": "datetime" },';
  $lines[] = '    { "name": "tc",      "type": "int" },';
  $lines[] = '    { "name": "tu",      "type": "int" }';
  $lines[] = '  ]';
  $lines[] = '}';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '`timestamps: true` → ogController agrega `dc/tc` en create, `du/tu` en update automáticamente.';
  $lines[] = 'Los campos dc/du/tc/tu deben estar en `fields[]` aunque el framework los rellene.';
  $lines[] = 'Para deshabilitar una ruta: agregar `"enabled": false` en esa ruta del schema.';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';
  $lines[] = '## QUÉ CUBRE ogController SOLO (sin Controller personalizado)';
  $lines[] = '';
  $lines[] = '```';
  $lines[] = 'list()      → filtra por $_GET (excepto page/per_page/sort/order), pagina, ordena';
  $lines[] = 'show($id)   → find($id), 404 automático';
  $lines[] = 'create()    → valida required del schema, agrega timestamps, insert';
  $lines[] = 'update($id) → verifica existencia, agrega timestamps, update';
  $lines[] = 'delete($id) → verifica existencia, delete';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = 'Si esto es suficiente, no crear Controller. Aplica a catálogos, tablas de config, etc.';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';
  $lines[] = '## CONTROLLER PERSONALIZADO';
  $lines[] = '';
  $lines[] = '```php';
  $lines[] = '<?php';
  $lines[] = 'class SaleController extends ogController {';
  $lines[] = '';
  $lines[] = '  function __construct() {';
  $lines[] = '    parent::__construct(\'sale\'); // nombre del schema — obligatorio siempre';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  // Solo sobreescribir lo que necesita cambio — el resto hereda de ogController';
  $lines[] = '';
  $lines[] = '  function create() {';
  $lines[] = '    $data = ogRequest::data();';
  $lines[] = '';
  $lines[] = '    // Validación custom + defaults';
  $lines[] = '    if (empty($data[\'amount\'])) {';
  $lines[] = '      ogResponse::json([\'success\' => false, \'error\' => __(\'sale.amount_required\')], 200);';
  $lines[] = '    }';
  $lines[] = '    $data[\'sale_type\']      = $data[\'sale_type\']      ?? \'main\';';
  $lines[] = '    $data[\'process_status\'] = $data[\'process_status\'] ?? \'initiated\';';
  $lines[] = '    $data[\'dc\'] = date(\'Y-m-d H:i:s\');';
  $lines[] = '    $data[\'tc\'] = time();';
  $lines[] = '';
  $lines[] = '    try {';
  $lines[] = '      $id = ogDb::t(\'sales\')->insert($data);';
  $lines[] = '      ogResponse::success([\'id\' => $id], __(\'sale.create.success\'), 201);';
  $lines[] = '    } catch (Exception $e) {';
  $lines[] = '      ogLog::error(\'SaleController::create\', [\'message\' => $e->getMessage()], [\'module\' => \'sale\']);';
  $lines[] = '      ogResponse::serverError(__(\'sale.create.error\'), OG_IS_DEV ? $e->getMessage() : null);';
  $lines[] = '    }';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  function list() {';
  $lines[] = '    $query = ogDb::t(\'sales\');';
  $lines[] = '';
  $lines[] = '    // Filtro por usuario autenticado (patrón común)';
  $lines[] = '    if (isset($GLOBALS[\'auth_user_id\'])) {';
  $lines[] = '      $query = $query->where(\'user_id\', $GLOBALS[\'auth_user_id\']);';
  $lines[] = '    }';
  $lines[] = '';
  $lines[] = '    // Join si necesita datos de otra tabla';
  $lines[] = '    // $query = $query->select([\'sales.*\', \'bots.name AS bot_name\'])';
  $lines[] = '    //   ->leftJoin(\'bots\', \'sales.bot_id\', \'=\', \'bots.id\');';
  $lines[] = '';
  $lines[] = '    foreach ($_GET as $key => $value) {';
  $lines[] = '      if (in_array($key, [\'page\', \'per_page\', \'sort\', \'order\'])) continue;';
  $lines[] = '      $query = $query->where($key, $value);';
  $lines[] = '    }';
  $lines[] = '';
  $lines[] = '    $data = $query';
  $lines[] = '      ->orderBy(ogRequest::query(\'sort\', \'id\'), ogRequest::query(\'order\', \'DESC\'))';
  $lines[] = '      ->paginate(ogRequest::query(\'page\', 1), ogRequest::query(\'per_page\', 50))';
  $lines[] = '      ->get();';
  $lines[] = '';
  $lines[] = '    ogResponse::success($data ?? []);';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  // Método extra — se llama desde app/routes/sale.php';
  $lines[] = '  function clone() {';
  $lines[] = '    $data = ogRequest::data();';
  $lines[] = '    // ...';
  $lines[] = '    ogResponse::success([\'id\' => $newId], __(\'sale.clone.success\'));';
  $lines[] = '  }';
  $lines[] = '}';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '**Reglas del Controller:**';
  $lines[] = '- `extends ogController` + `parent::__construct(\'schema\')` — obligatorio';
  $lines[] = '- Sobreescribir solo los métodos que cambian';
  $lines[] = '- Timestamps manuales: `dc/tc` en create, `du/tu` en update';
  $lines[] = '- Siempre `try/catch` en operaciones DB';
  $lines[] = '- Respuesta siempre via `ogResponse::*`';
  $lines[] = '- Los métodos extra se llaman desde `routes/{modulo}.php`';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';
  $lines[] = '## HANDLER';
  $lines[] = '';
  $lines[] = '```php';
  $lines[] = '<?php';
  $lines[] = 'class SaleHandler {';
  $lines[] = '';
  $lines[] = '  private static $logMeta = [\'module\' => \'SaleHandler\', \'layer\' => \'app/resources\'];';
  $lines[] = '';
  $lines[] = '  // Sin extends — clase pura PHP';
  $lines[] = '  // Todos los métodos static — nunca se instancia directamente';
  $lines[] = '  // Retorna arrays con success/data/error — nunca llama ogResponse';
  $lines[] = '';
  $lines[] = '  static function getByClient($params) {';
  $lines[] = '    $sales = ogDb::t(\'sales\')';
  $lines[] = '      ->where(\'client_id\', $params[\'client_id\'])';
  $lines[] = '      ->orderBy(\'dc\', \'DESC\')';
  $lines[] = '      ->limit(ogRequest::query(\'limit\', 50))';
  $lines[] = '      ->get();';
  $lines[] = '    return [\'success\' => true, \'data\' => $sales ?? []];';
  $lines[] = '  }';
  $lines[] = '';
  $lines[] = '  static function updateStatus($saleId, $status) {';
  $lines[] = '    $sale = ogDb::t(\'sales\')->find($saleId);';
  $lines[] = '    if (!$sale) return [\'success\' => false, \'error\' => __(\'sale.not_found\')];';
  $lines[] = '    try {';
  $lines[] = '      ogDb::t(\'sales\')->where(\'id\', $saleId)->update([';
  $lines[] = '        \'process_status\' => $status,';
  $lines[] = '        \'du\' => date(\'Y-m-d H:i:s\'),';
  $lines[] = '        \'tu\' => time()';
  $lines[] = '      ]);';
  $lines[] = '      return [\'success\' => true];';
  $lines[] = '    } catch (Exception $e) {';
  $lines[] = '      return [\'success\' => false, \'error\' => $e->getMessage()];';
  $lines[] = '    }';
  $lines[] = '  }';
  $lines[] = '}';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '**Cómo llamar al Handler:**';
  $lines[] = '';
  $lines[] = '```php';
  $lines[] = '// Desde rutas — handler() carga + retorna instancia, PHP permite instancia::static';
  $lines[] = 'ogResponse::json(ogApp()->handler(\'sale\')::getByClient([\'client_id\' => $id]));';
  $lines[] = '';
  $lines[] = '// Desde Controller — loadHandler() carga el archivo, luego llama static directamente';
  $lines[] = 'ogApp()->loadHandler(\'product\');';
  $lines[] = 'ProductHandler::handleByContext($data, \'create\');';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';
  $lines[] = '## RUTAS CUSTOM — app/routes/{modulo}.php';
  $lines[] = '';
  $lines[] = '```php';
  $lines[] = '<?php';
  $lines[] = '// app/routes/sale.php';
  $lines[] = '// Las 5 rutas CRUD se auto-registran desde sale.json — NO redeclararlas aquí';
  $lines[] = '';
  $lines[] = '$router->group(\'/api/sale\', function($router) {';
  $lines[] = '';
  $lines[] = '  // Delegar al Handler';
  $lines[] = '  $router->get(\'/client/{client_id}\', function($client_id) {';
  $lines[] = '    ogResponse::json(ogApp()->handler(\'sale\')::getByClient([\'client_id\' => $client_id]));';
  $lines[] = '  })->middleware([\'auth\', \'throttle:100,1\']);';
  $lines[] = '';
  $lines[] = '  // Delegar a método extra del Controller';
  $lines[] = '  $router->post(\'/clone\', function() {';
  $lines[] = '    ogApp()->controller(\'sale\')->clone();';
  $lines[] = '  })->middleware([\'auth\', \'json\']);';
  $lines[] = '';
  $lines[] = '  // Lógica inline si es puntual y no se reutiliza';
  $lines[] = '  $router->put(\'/{id}/status\', function($id) {';
  $lines[] = '    $status = ogRequest::data()[\'status\'] ?? null;';
  $lines[] = '    if (!$status) ogResponse::json([\'success\' => false, \'error\' => __(\'sale.status_required\')], 400);';
  $lines[] = '    ogResponse::json(ogApp()->handler(\'sale\')::updateStatus($id, $status));';
  $lines[] = '  })->middleware([\'auth\', \'json\', \'throttle:100,1\']);';
  $lines[] = '';
  $lines[] = '});';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';
  $lines[] = '## CHECKLIST';
  $lines[] = '';
  $lines[] = '```';
  $lines[] = '□ 1. app/resources/schemas/{modulo}.json';
  $lines[] = '       resource, table, timestamps: true, middleware global,';
  $lines[] = '       5 rutas CRUD con sus middleware, fields (timestamps al final)';
  $lines[] = '';
  $lines[] = '□ 2. ¿ogController cubre todo?';
  $lines[] = '       SÍ → fin, no crear más archivos';
  $lines[] = '       NO → app/resources/controllers/{Modulo}Controller.php';
  $lines[] = '            extends ogController + parent::__construct + solo métodos que cambian';
  $lines[] = '';
  $lines[] = '□ 3. ¿Side-effects o lógica reutilizable?';
  $lines[] = '       SÍ → app/resources/handlers/{Modulo}Handler.php';
  $lines[] = '            sin extends, todos static, retorna arrays, nunca ogResponse';
  $lines[] = '       NO → no crear Handler';
  $lines[] = '';
  $lines[] = '□ 4. ¿Endpoints fuera del CRUD estándar?';
  $lines[] = '       SÍ → app/routes/{modulo}.php — solo los extras';
  $lines[] = '       NO → no crear routes/{modulo}.php';
  $lines[] = '```';
  $lines[] = '';
  $lines[] = '---';
  $lines[] = '';
  $lines[] = '## ERRORES COMUNES';
  $lines[] = '';
  $lines[] = '```';
  $lines[] = 'NO crear Controller sin que exista el schema      → fatal en parent::__construct';
  $lines[] = 'NO redeclarar las 5 rutas CRUD en routes/         → ya son automáticas del schema';
  $lines[] = 'NO olvidar parent::__construct(\'modulo\')          → el Controller falla sin esto';
  $lines[] = 'NO usar métodos de instancia en Handler           → deben ser static';
  $lines[] = 'NO llamar ogResponse dentro del Handler           → solo en Controller y rutas';
  $lines[] = 'NO hardcodear paths absolutos                     → ogApp()->getPath(\'storage/...\')';
  $lines[] = 'NO instanciar helpers directamente                → ogApp()->helper(\'nombre\')';
  $lines[] = '```';

  // ── Armar prompt ──────────────────────────────────────────────
  $md   = [];
  $md[] = '# Backend — Playbook CRUD & Módulos';
  $md[] = '';
  $md[] = '> Cómo crear un módulo CRUD. Cuándo crear cada archivo, dónde va, por qué.';
  $md[] = '> Generado: ' . date('Y-m-d H:i:s');
  $md[] = '';
  $md[] = '---';
  $md[] = '';
  $md[] = implode("\n", $lines);

  file_put_contents($promptsPath . '/crud.prompt.md', implode("\n", $md));
  $generated[] = '.github/prompts/crud.prompt.md';

  return compact('generated');
}